import { useState } from 'react';
import styles from './ContactForm.module.css';
import SuccessModal from '../SuccessModal/SuccessModal';

export default function ContactForm() {
  const [formData, setFormData] = useState({
    name: '',
    messengerContact: '',
    email: '',
    teamSize: '20-40',
    challenge: ''
  });


  const [errors, setErrors] = useState({
    name: '',
    messengerContact: '',
    email: '',
    teamSize: ''
  });

  const [touched, setTouched] = useState({
    name: false,
    messengerContact: false,
    email: false,
    teamSize: false
  });

  const [showSuccessModal, setShowSuccessModal] = useState(false);
  const [isSubmitting, setIsSubmitting] = useState(false);

  const teamSizeOptions = [
    { value: '20-40', label: '20-40' },
    { value: '40-60', label: '40-60' },
    { value: '60-100', label: '60-100' },
    { value: '100+', label: '100+' }
  ];

  const validateField = (name, value) => {
    switch (name) {
      case 'name':
        if (!value.trim()) {
          return 'Name is required';
        }
        return '';
      case 'messengerContact':
        if (!value.trim()) {
          return 'Messenger contact is required';
        }
        return '';
      case 'email':
        if (!value.trim()) {
          return 'Email is required';
        }
        const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
        if (!emailRegex.test(value)) {
          return 'Please enter a valid email';
        }
        return '';
      case 'teamSize':
        if (!value) {
          return 'Team size is required';
        }
        return '';
      default:
        return '';
    }
  };

  const handleChange = (e) => {
    const { name, value } = e.target;
    setFormData(prev => ({ ...prev, [name]: value }));

    // Validate on change if field has been touched
    if (touched[name]) {
      setErrors(prev => ({ ...prev, [name]: validateField(name, value) }));
    }
  };

  const handleBlur = (e) => {
    const { name, value } = e.target;
    setTouched(prev => ({ ...prev, [name]: true }));
    setErrors(prev => ({ ...prev, [name]: validateField(name, value) }));
  };


  const handleSubmit = async (e) => {
    e.preventDefault();

    // Validate all fields
    const newErrors = {
      name: validateField('name', formData.name),
      messengerContact: validateField('messengerContact', formData.messengerContact),
      email: validateField('email', formData.email),
      teamSize: validateField('teamSize', formData.teamSize)
    };

    setErrors(newErrors);
    setTouched({ name: true, messengerContact: true, email: true, teamSize: true });

    // Check if there are any errors
    const hasErrors = Object.values(newErrors).some(error => error !== '');

    if (!hasErrors) {
      setIsSubmitting(true);
      try {
        const submissionData = {
          name: formData.name,
          messenger_contact: formData.messengerContact,
          email: formData.email,
          team_size: formData.teamSize,
          biggest_challenge: formData.challenge || null
          // device_type will be detected by Edge Function
          // submitted_at is auto-generated by database
        };

        // Submit to Edge Function (more secure than direct database access)
        const response = await fetch(
          `${import.meta.env.VITE_SUPABASE_URL}/functions/v1/submit-form`,
          {
            method: 'POST',
            headers: {
              'Content-Type': 'application/json',
              'Authorization': `Bearer ${import.meta.env.VITE_SUPABASE_ANON_KEY}`,
            },
            body: JSON.stringify(submissionData),
          }
        );

        if (!response.ok) {
          alert('Failed to submit form. Please try again.');
          setIsSubmitting(false);
          return;
        }

        await response.json();

        // Show success modal
        setShowSuccessModal(true);
        setIsSubmitting(false);
      } catch (error) {
        alert('Failed to submit form. Please try again.');
        setIsSubmitting(false);
      }
    }
  };

  const handleCloseModal = () => {
    setShowSuccessModal(false);

    // Reset form
    setFormData({
      name: '',
      messengerContact: '',
      email: '',
      teamSize: '20-40',
      challenge: ''
    });
    setTouched({ name: false, messengerContact: false, email: false, teamSize: false });
  };

  return (
    <section id="contact-form" className={styles.contactFormSection}>
      <div className={styles.container}>
        <div className={styles.content}>
          <h2 className={styles.heading}>
            Let's have a demo call and get to know each other
          </h2>

          <form className={styles.formCard} onSubmit={handleSubmit} noValidate>
            <div className={styles.formFieldsWrapper}>
              {/* Name Field */}
              <div className={styles.formField}>
                <label htmlFor="name" className={styles.label}>
                  Name
                </label>
                <input
                  type="text"
                  id="name"
                  name="name"
                  value={formData.name}
                  onChange={handleChange}
                  onBlur={handleBlur}
                  placeholder="William"
                  className={`${styles.input} ${errors.name && touched.name ? styles.inputError : ''}`}
                />
                {errors.name && touched.name && (
                  <span className={styles.errorMessage}>{errors.name}</span>
                )}
              </div>

              {/* Messenger Contact Field */}
              <div className={styles.formField}>
                <label htmlFor="messengerContact" className={styles.label}>
                  Messenger contact
                </label>
                <input
                  type="text"
                  id="messengerContact"
                  name="messengerContact"
                  value={formData.messengerContact}
                  onChange={handleChange}
                  onBlur={handleBlur}
                  placeholder="Telegram/WhatsApp/other"
                  className={`${styles.input} ${errors.messengerContact && touched.messengerContact ? styles.inputError : ''}`}
                />
                {errors.messengerContact && touched.messengerContact && (
                  <span className={styles.errorMessage}>{errors.messengerContact}</span>
                )}
              </div>

              {/* Email Field */}
              <div className={styles.formField}>
                <label htmlFor="email" className={styles.label}>
                  Email
                </label>
                <input
                  type="email"
                  id="email"
                  name="email"
                  value={formData.email}
                  onChange={handleChange}
                  onBlur={handleBlur}
                  placeholder="William@gmail.com"
                  className={`${styles.input} ${errors.email && touched.email ? styles.inputError : ''}`}
                />
                {errors.email && touched.email && (
                  <span className={styles.errorMessage}>{errors.email}</span>
                )}
              </div>

              {/* Team Size Field */}
              <div className={styles.formField}>
                <label htmlFor="teamSize" className={styles.label}>
                  Team size
                </label>
                <div className={styles.selectWrapper}>
                  <select
                    id="teamSize"
                    name="teamSize"
                    value={formData.teamSize}
                    onChange={handleChange}
                    onBlur={handleBlur}
                    className={`${styles.select} ${errors.teamSize && touched.teamSize ? styles.inputError : ''}`}
                  >
                    <option value="">Select team size</option>
                    {teamSizeOptions.map(option => (
                      <option key={option.value} value={option.value}>
                        {option.label}
                      </option>
                    ))}
                  </select>
                  <img
                    src="/images/contact-form/chevron-down.svg"
                    alt=""
                    className={styles.chevronIcon}
                  />
                </div>
                {errors.teamSize && touched.teamSize && (
                  <span className={styles.errorMessage}>{errors.teamSize}</span>
                )}
              </div>

              {/* Challenge Field (Optional) */}
              <div className={styles.formField}>
                <label htmlFor="challenge" className={styles.label}>
                  Biggest challenge (optional)
                </label>
                <textarea
                  id="challenge"
                  name="challenge"
                  value={formData.challenge}
                  onChange={handleChange}
                  placeholder="We grew from 30 to 45 people this year but profit stayed flat. Something's broken but I can't see where..."
                  className={styles.textarea}
                  rows={5}
                />
              </div>
            </div>

            {/* CTA Container */}
            <div className={styles.ctaContainer}>
              <button
                type="submit"
                className={styles.submitButton}
                disabled={isSubmitting}
              >
                {isSubmitting ? 'Sending...' : 'Book my demo'}
              </button>
              <div className={styles.ctaInfo}>
                <p className={styles.ctaTextTop}>
                  30-minute call with <span className={styles.cofounderText}>CEO and Co-founder</span>
                </p>
                <div className={styles.ctaFounderRow}>
                  <img
                    src="/images/proven-solution/george-avatar.png"
                    alt="George Kachanouski"
                    className={styles.avatar}
                  />
                  <a
                    href="https://www.linkedin.com/in/georgekachanouski/"
                    target="_blank"
                    rel="noopener noreferrer"
                    className={styles.ctaLink}
                  >
                    George Kachanouski
                  </a>
                </div>
              </div>
            </div>
          </form>
        </div>

        {/* Decorative Image */}
        <div className={styles.decorativeImage}>
          <img
            src="/images/contact-form/George pointing.png"
            alt="George pointing"
            className={styles.decorativeImg}
          />
        </div>
      </div>

      {/* Success Modal */}
      {showSuccessModal && (
        <SuccessModal
          userName={formData.name}
          onClose={handleCloseModal}
        />
      )}
    </section>
  );
}
